import os
from pathlib import Path

import pandas as pd
import plotly.express as px
import streamlit as st
from sqlalchemy import create_engine, text


st.set_page_config(page_title="StreamFlow Analytics", layout="wide")
st.title("StreamFlow Analytics Frontend")
st.caption("Explore Postgres tables and files generated by the pipeline.")


def get_db_url() -> str:
    host = os.getenv("POSTGRES_HOST", "postgres")
    port = os.getenv("POSTGRES_PORT", "5432")
    db = os.getenv("POSTGRES_DB", "airflow")
    user = os.getenv("POSTGRES_USER", "airflow")
    password = os.getenv("POSTGRES_PASSWORD", "airflow")
    return f"postgresql+psycopg2://{user}:{password}@{host}:{port}/{db}"


@st.cache_resource
def get_engine():
    return create_engine(get_db_url(), pool_pre_ping=True)


def query_df(sql: str) -> pd.DataFrame:
    with get_engine().connect() as conn:
        return pd.read_sql(text(sql), conn)


tab_db, tab_files = st.tabs(["Postgres Explorer", "Landing/Gold Files"])

with tab_db:
    st.subheader("Postgres Explorer")
    sql_default = "SELECT table_schema, table_name FROM information_schema.tables ORDER BY 1, 2 LIMIT 100;"
    sql = st.text_area("SQL query", value=sql_default, height=120)

    run = st.button("Run Query")
    if run:
        try:
            df = query_df(sql)
            st.success(f"Rows returned: {len(df)}")
            st.dataframe(df, use_container_width=True)

            if not df.empty:
                numeric_cols = df.select_dtypes(include="number").columns.tolist()
                if numeric_cols:
                    y_col = st.selectbox("Quick chart numeric column", numeric_cols, key="chart_y")
                    chart_df = df[[y_col]].copy().reset_index()
                    fig = px.line(chart_df, x="index", y=y_col, title=f"{y_col} trend")
                    st.plotly_chart(fig, use_container_width=True)
        except Exception as exc:
            st.error(f"Query failed: {exc}")


with tab_files:
    st.subheader("Landing/Gold Files")
    data_root = Path(os.getenv("DATA_ROOT", "/opt/spark-data"))
    landing = data_root / "landing"
    gold = data_root / "gold"

    st.write(f"Data root: `{data_root}`")

    candidates = []
    for folder in [landing, gold]:
        if folder.exists():
            for pattern in ("*.json", "*.csv", "*.parquet"):
                candidates.extend(folder.rglob(pattern))

    if not candidates:
        st.info("No landing/gold files found yet.")
    else:
        selected = st.selectbox("Select file", sorted(str(p) for p in candidates))
        selected_path = Path(selected)
        st.write(f"Selected: `{selected_path}`")

        try:
            if selected_path.suffix.lower() == ".json":
                df = pd.read_json(selected_path, lines=True)
            elif selected_path.suffix.lower() == ".csv":
                df = pd.read_csv(selected_path)
            elif selected_path.suffix.lower() == ".parquet":
                df = pd.read_parquet(selected_path)
            else:
                df = pd.DataFrame()

            st.dataframe(df.head(1000), use_container_width=True)
            st.write(f"Rows loaded (sample): {len(df)}")
        except Exception as exc:
            st.error(f"Could not read file: {exc}")
